name: app
description: A sample Flutter project using GitHub API

dependencies:
  flutter:
    sdk: flutter
  fluro: "^1.2.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
